version: "3.3"

services:
  registrar:
    hostname: registrar
    container_name: registrar
    build:
      context: ./registrar
    networks:
      - voipnetwork
    ports:
      - '8080:8080'
    expose:
      - '8080'
    restart: unless-stopped

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - voipnetwork
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: {}

networks:
  voipnetwork: